# Generated by Django 5.1.7 on 2025-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensatoryday',
            name='note',
            field=models.TextField(blank=True, help_text='Justification note for this compensation (if any)', null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='deduction_done',
            field=models.BooleanField(default=False, help_text='Indicates if vacation discount has been applied after return.'),
        ),
    ]
