# Generated by Django 5.1.7 on 2025-03-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_compensatoryday_note_vacationrequest_deduction_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensatoryday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
